#!/bin/sh

# extract time digit from a log file and convert it to the meaningful string.
if [ $# -ne 1 ]; then
   echo "exltime <log file name>"
   exit
fi

file=$1
file2=${file##*_}
awstime=${file2%.*}

t2str $awstime
